net/mac/csma: Rename `free_packet()` to something less likely to cause conflict.
This fixes errors like this:

    ../../core/net/mac/csma.c:167: error: conflicting types for 'free_packet'
    ../../cpu/mc1322x/lib/include/maca.h:74: error: previous declaration of 'free_packet' was here
    make[1]: *** [obj_econotag/csma.o] Error 1