Fixing Avr-Zigbit Makefile not compiling
Fixed two errors in Zigbit's makefile:
-Compiling "frame.c" here is not necessary (already done in radio's makefile) and brings up an error. Removing it.
-Fixed undefined reference to "link_stats_input_callback" in "../../core/net/ipv6/sicslowpan.c:1521". Module "core/net" was missing.
Compiling working now.